# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efd7157079080507f586d0eb9a22a5c69b08e0f4f40d72935fbec3ffdb468de0773d2516047b1102296e55c3d8cb246c042c9e4ab3c2b172b85e68cd5edf61da

test:
  secret_key_base: ec9b765f08d15ca80921d75a47786cbb87a99c50ebe1a0d82cac6d6389c2d7a0f2dc8b4e205c0c7fb5bb424d6098a278003eebb44580d75773b398fe64f1ce40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
